<?php

/**
 * TurboDepot is a cross language ORM library that allows saving, retrieving, listing, filtering and more with complex class data instances
 *
 * Website : -> http://www.turbodepot.org
 * License : -> Licensed under the Apache License, Version 2.0. You may not use this file except in compliance with the License.
 * License Url : -> http://www.apache.org/licenses/LICENSE-2.0
 * CopyRight : -> Copyright 2017 Edertone Advanded Solutions (Barcelona). http://www.edertone.com
 */

namespace org\turbodepot\src\main\php\model;


/**
 * The base class to use with objects that need to be saved to TurboDepot.
 * For example: To store an invoice, we must create an Invoice class that extends TurboDepotEntity and define our
 * custom properties; we will then be able to save as many instances of it as we want.
 */
abstract class TurboDepotEntity {


	/**
	 * Each TurboDepot entity has a unique identifier that can be used to search or recover previously saved instances.
	 * When an instance is saved for the first time, the id is autogenerated with a value that will never change.<br>
	 *
	 * Several identifier creation policies are available. To specify how unique identifiers are generated for all the instances of
	 * the same class, the id property value can be defined with diferent default values when extending the base TurboDepotEntity. Depending
	 * on the default id value, an identifier creation policy will be chosen. Possible default id values are:<br>
	 *
	 * - '' to generate all instance ids as Universally unique identifiers (UUID). This guarantees portability and prevents collisions and is the default setting if the id property is not overriden.<br><br>
	 * - 0 to generate all instance ids as autonumeric integer values, starting at 1. This creates smaller ids that improve performance, but are less secure and may collide.<br>
	 *
	 * Any entity that has never been saved will have an empty or 0 id value depending on the id generation policy that's been chosen.
	 * Note: It is possible to change the id generation policy after one or more entity instances have been saved to database,
	 * but it is not recommended to mix different types of unique ids on the same class of objects.
	 *
	 * @see https://en.wikipedia.org/wiki/Universally_unique_identifier
	 */
	public $id = '';


	/**
	 * Contains the date and time (ISO 8601 format with microseconds precision) when this entity was first stored.
	 * An entity that has not been yet stored to TurboDepot will have an empty ('') value here.
	 * This value does not change during the entity lifetime.
	 */
	public $creationDate = '';


	/**
	 * Contains the date and time (ISO 8601 format with microseconds precision) when this entity was last modified.
	 * An entity that has not been yet stored to TurboDepot will have an empty ('') value here.
	 */
	public $modificationDate = '';


	/**
	 * When TurboDepot Recycle Bin feature is enabled, deleted entities are moved to trash instead of
	 * being permanently deleted.
	 */
	// TODO: define recycle bin feature and decide what to do with this property.
	//public $deleted = false;


	/**
	 * TODO
	 */
	public function setLocale($locale){

	    // TODO - Copy values for properties that have been set with different values than their defaults
	    // Except those that cannot be localized like id, creation date...
	    foreach ($listOfClassProperties as $property => $value) {

	        if($value != $propertyDefaultValue){

	            $htis->localizedData[$this->locale][$property] = $value;
	        }
	    }

	    // TODO - Restore values for the new locale if exist
	    foreach ($htis->localizedData[$locale] as $property => $value) {

	        $htis[$property] = $value;
	    }

	    // TODO - Change the defined locale to the new one
	    $this->locale = $locale;
	}


	/**
	 * TODO - Store the different localized values for the properties
	 */
	private $localizedData = [];


	/**
	 * TODO
	 */
	private $locale = '';


	// TODO - all limitations will be defined at TurboDepot.xml file

}

?>